# Generated by Django 5.1.4 on 2025-01-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
