# Generated by Django 5.1.4 on 2025-01-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='roads',
            name='engineerMessage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roads',
            name='isUploadedProof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roads',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='qms_app.milestones'),
        ),
    ]
