# Generated by Django 5.1.4 on 2025-01-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0003_roads_engineermessage_roads_isuploadedproof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedEvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='qms_app.roads')),
            ],
        ),
    ]
