# Generated by Django 5.1.4 on 2025-01-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0004_uploadedevidencefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedevidencefile',
            name='milestone_name',
        ),
        migrations.RemoveField(
            model_name='uploadedevidencefile',
            name='road',
        ),
        migrations.AddField(
            model_name='uploadedevidencefile',
            name='milestone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='qms_app.milestones'),
        ),
        migrations.AddField(
            model_name='uploadedevidencefile',
            name='road_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='qms_app.roads'),
        ),
        migrations.AlterField(
            model_name='uploadedevidencefile',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
